import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Image from 'next/image';
import Contact from '../components/contact';

export default function Home() {
  return (
    <div className={styles.container}>
      
      
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header>
          <h1 className={styles.title}>
            My Portfolio
          </h1>
          <hr className={styles.hr}/>
          <p className={styles.description}>
            Hello there,
            <br/>
            Am Chris Brian <br/>
            This is my simple portfolio
          </p>
        </header>
        <div className={styles.whitesection}>
          <section className={styles.whoiam}>
            <span className={styles.secimg}>
               <Image src="/1.jpg" height={250} width={400}/>
            </span>
            <h1 className={styles.title}>
               WHO AM I
            </h1>
            <hr className={styles.hr}/>
            <p className={styles.description}>
            Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. 
            Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate
             phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum.
            </p>
          </section>
          
        </div>
        <section className={styles.portfolio}>
          <div className={styles.bluesection}>
            <span className={styles.secimg}>
               <Image src="/2.jpg" height={250} width={400}/>
            </span>
            <h1 className={styles.title}>
               Stuff I Do
            </h1>
            <hr className={styles.hr}/>
            <p className={styles.description}>
            Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. 
            Consequat sed ultricies rutrum. 
            </p> 
           <div className={styles.grid}>
             <div className={styles.cards}>
             <div className={styles.card}>
              
                </div>
                <h2> Events photography</h2>
             </div>
             <div className={styles.cards}>
             <div className={styles.card}>
            
            </div>
            <h2> Drone Shoots </h2>
             </div>
            </div>
            <div className={styles.grid}>
             <div className={styles.cards}>
             <div className={styles.card}>
            
                </div>
                <h2> Advertisement</h2>
             </div>
             <div className={styles.cards}>
             <div className={styles.card}>
           
            </div>
            <h2> Wallpapers </h2>
             </div>
            </div>
          </div>
        </section>  
        <section className={styles.resume}>
          <div className={styles.whitesection}>
            <span className={styles.secimg}>
               <Image src="/7.jpg" height={250} width={400}/>
            </span>
            <h1 className={styles.title}>
               Resume
            </h1>
            <hr className={styles.hr}/>
            <p className={styles.description}>
            Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. 
            Consequat sed ultricies rutrum. 
            </p> 
            <button className={styles.button}>
              Resume
            </button>
          </div>
        </section> 
        <Contact/>
        </main>
        
    </div>
  )
}
