import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Footers from '../components/Footer';
import Nav from '../components/Nav';
import Layout from '../components/Layout';
import Image from 'next/image';


export default function Home() {
  return (
    <div className={styles.container}>
      
      <Nav />
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout />
         <Footers/>
    </div>
  )
}
