import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Image from 'next/image';
import Contact from '../components/contact';

export default function Home() {
  return (
    <div className={styles.container}>
      
      
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header>
          <h1 className={styles.title}>
            My Portfolio
          </h1>
          <hr className={styles.hr}/>
          <p className={styles.description}>
            Hello there,
            <br/>
           Just showcasing my skills
          </p>
        </header>
        <div className={styles.whitesection}>
          <section className={styles.whoiam}>
            <span className={styles.secimg}>
               <Image src="/about.jpeg" height={500} width={400}/>
            </span>
            <h1 className={styles.title}>
               WHO AM I
            </h1>
            <hr className={styles.hr}/>
            <p className={styles.description}>
            Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. 
            Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate
             phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum.
            </p>
            <div className={styles.buttonsec}>
            <div className={styles.downsec}>
            <button className={styles.downbutton}>
              Download cv
            </button>
            </div>
            <div className={styles.hiresec}></div>
             <a href='#'>
             <button className={styles.hirebutton}>
              Hire me
            </button>
             </a> 
            </div>
          </section>
          
        </div>
        <section className={styles.portfolio}>
          <div className={styles.whitesection}>
            <span className={styles.secimg}>
               <Image src="/2.jpg" height={250} width={400}/>
            </span>
            <h1 className={styles.title}>
               STUFF I DO
            </h1>
            <hr className={styles.hr}/>
            <p className={styles.description}>
            Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. 
            Consequat sed ultricies rutrum. 
            </p> 
           <div className={styles.grid}>
             <div className={styles.cards}>
             <div className={styles.card}>
               <Image src="/3.jpg" height={300} width={400}/>
                </div>
                <h2> Events photography</h2>
             </div>
             <div className={styles.cards}>
             <div className={styles.card}>
             <Image src="/4.jpg" height={300} width={400}/>
            </div>
            <h2> Drone Shoots </h2>
             </div>
            </div>
            <div className={styles.grid}>
             <div className={styles.cards}>
             <div className={styles.card}>
             <Image src="/5.jpg" height={300} width={400}/>
                </div>
                <h2> Advertisement</h2>
             </div>
             <div className={styles.cards}>
             <div className={styles.card}>
             <Image src="/6.jpg" height={300} width={400}/>
            </div>
            <h2> Wallpapers </h2>
             </div>
            </div>
          </div>
        </section>  
        <section className={styles.resume}>
          <div className={styles.whitesection}>
            <span className={styles.secimg}>
               <Image src="/7.jpg" height={250} width={400}/>
            </span>
            <h1 className={styles.title}>
               RESUME
            </h1>
            <hr className={styles.hr}/>
            <p className={styles.description}>
            Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. 
            Consequat sed ultricies rutrum. 
            </p> 
            <button className={styles.button}>
              Resume
            </button>
          </div>
        </section> 
        <Contact/>
        </main>
        
    </div>
  )
}
